ktor {
  deployment {
    host = "0.0.0.0"
    port = 8080
  }

  application {
    modules = [ com.example.mutlabocnotes.ApplicationKt.module ]
  }
}

db {
  driverClassName = org.postgresql.Driver
  jdbcUrl = ${DB_JDBC_URL}
  username = ${DB_USERNAME}
  password = ${DB_PASSWORD}

  maximumPoolSize = 10
  minimumIdle = 2

  connectionTimeoutMs = 10000
  idleTimeoutMs = 600000
  maxLifetimeMs = 1800000

  autoCommit = false
}

jwt {
  issuer = "notes-backend"
  audience = "notes-android"
  realm = "notes-api"
  secret = ${?JWT_SECRET}
  accessTokenTtlSeconds = 1800
  refreshTokenTtlSeconds = 1209600
}

flyway {
  enabled = true
  locations = ["classpath:db/migration"]
  validateMigrationNaming = true
}

socialAuth {
  google {
    webClientId = ${?GOOGLE_WEB_CLIENT_ID}
  }

  yandex {
    clientId = ${?YANDEX_CLIENT_ID}
    clientSecret = ${?YANDEX_CLIENT_SECRET}
  }
}
